import { StyleSheet } from 'react-native';

export const appStyles = StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: '#fff' },
    appContainer: { flex: 1 },
    flexContainer: { flex: 1 },
    container: { flex: 1, padding: 20 },
    landingContainer: { flex: 1, justifyContent: 'center', padding: 40 },
    heroContent: { alignItems: 'center', marginBottom: 60 },
    brandBadge: { backgroundColor: '#EEF2FF', color: '#4F46E5', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12, fontSize: 12, fontWeight: '600', marginBottom: 12, overflow: 'hidden' },
    heroTitle: { fontSize: 32, fontWeight: '800', color: '#1E293B', marginBottom: 16, textAlign: 'center' },
    heroSubtitle: { fontSize: 16, color: '#64748B', textAlign: 'center', lineHeight: 24 },
    buttonGroup: { gap: 15 },
    introBox: { backgroundColor: '#F8FAFC', padding: 20, borderRadius: 16, alignItems: 'center', borderStyle: 'dashed', borderWidth: 1, borderColor: '#CBD5E1' },
    introText: { color: '#64748B', fontSize: 14, textAlign: 'center' },
    adminEntry: { marginTop: 30, alignItems: 'center' },
    adminEntryText: { color: '#94A3B8', fontSize: 14, textDecorationLine: 'underline' },
    adminActionRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
    adminTitle: { fontSize: 24, fontWeight: '700', color: '#1E293B' },
    mgmtBtn: { backgroundColor: '#F1F5F9', padding: 8, borderRadius: 8 },
    mgmtBtnText: { color: '#475569', fontWeight: '600' },
    branchCardRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    branchName: { fontSize: 18, fontWeight: '700', color: '#1E293B' },
    branchSlug: { fontSize: 13, color: '#64748B' },
    branchHint: { fontSize: 11, color: '#94A3B8', marginTop: 4 },
    linkBtn: { backgroundColor: '#E0F2FE', padding: 10, borderRadius: 8 },
    linkBtnText: { color: '#0369A1', fontSize: 13, fontWeight: '700' },
    logItem: { paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#F1F5F9', flexDirection: 'row', alignItems: 'center' },
    logName: { fontWeight: '700', color: '#1E293B' },
    logSender: { fontSize: 13, color: '#64748B', lineHeight: 18 },
    logInfo: { fontSize: 12, color: '#94A3B8', marginTop: 2 },
    emptyText: { textAlign: 'center', color: '#94A3B8', marginVertical: 20 },
    previewImage: { width: '100%', height: 260, borderRadius: 12, marginTop: 15 },
    retakeBtn: { position: 'absolute', bottom: 10, right: 10, backgroundColor: 'rgba(0,0,0,0.6)', padding: 8, borderRadius: 8 },
    retakeBtnText: { color: '#fff', fontSize: 12, fontWeight: '600' },
    inputGroup: { marginBottom: 20 },
    label: { fontSize: 14, fontWeight: '600', color: '#64748B', marginBottom: 8 },
    input: { backgroundColor: '#F8FAFC', borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 8, padding: 12, fontSize: 16, color: '#1E293B' },
    profileSelector: { marginTop: 4 },
    matchedBox: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#F0FDF4', padding: 12, borderRadius: 8, borderWidth: 1, borderColor: '#BBF7D0' },
    matchedText: { color: '#166534', fontWeight: '700', fontSize: 14 },
    changeText: { color: '#4F46E5', fontSize: 12, fontWeight: '600' },
    profileList: { marginTop: 4 },
    profileChip: { backgroundColor: '#F1F5F9', paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, marginRight: 8, borderWidth: 1, borderColor: '#E2E8F0' },
    profileChipText: { color: '#475569', fontWeight: '600' },
    typeList: { marginTop: 4 },
    typeChip: { backgroundColor: '#F1F5F9', paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, marginRight: 8, borderWidth: 1, borderColor: '#E2E8F0' },
    typeChipActive: { backgroundColor: '#4F46E5', borderColor: '#4F46E5' },
    typeChipText: { color: '#475569', fontWeight: '600' },
    typeChipTextActive: { color: '#fff' },

    // New Dashboard Styles
    quickActionContainer: { flexDirection: 'row', gap: 12, marginBottom: 24 },
    quickActionButton: { flex: 1, padding: 20, borderRadius: 24, alignItems: 'center', elevation: 4, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.15, shadowRadius: 8 },
    iconCircle: { width: 64, height: 64, backgroundColor: 'rgba(255,255,255,0.2)', borderRadius: 32, justifyContent: 'center', alignItems: 'center', marginBottom: 12 },
    quickActionTitle: { fontSize: 16, fontWeight: '800', color: '#fff', marginBottom: 4 },
    quickActionDesc: { fontSize: 11, color: 'rgba(255,255,255,0.8)', textAlign: 'center' },
    shareLinkCompact: { backgroundColor: '#EEF2FF', padding: 16, borderRadius: 16, marginBottom: 24, borderWidth: 1, borderColor: '#C7D2FE' },

    // Premium Landing Styles
    premiumLine: { width: 40, height: 3, backgroundColor: '#1E293B', marginBottom: 24, borderRadius: 2 },
    actionSection: { width: '100%', marginTop: 20 },
    tenantHint: { textAlign: 'center', fontSize: 13, color: '#94A3B8', lineHeight: 20 },
    loginCardDirect: {
        backgroundColor: '#fff',
        padding: 24,
        borderRadius: 30,
        borderWidth: 1,
        borderColor: '#F1F5F9',
        elevation: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.05,
        shadowRadius: 20,
    },
    loginDirectTitle: { fontSize: 18, fontWeight: '800', color: '#1E293B', marginBottom: 24, textAlign: 'center' },

    // Admin Branch Select Premium Styles
    adminTitleText: { fontSize: 22, fontWeight: '800', color: '#1E293B' },
    professionalMgmtBtn: {
        backgroundColor: '#F1F5F9',
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#E2E8F0'
    },
    professionalMgmtBtnText: { color: '#475569', fontSize: 13, fontWeight: '700' },
    branchNameText: { fontSize: 18, fontWeight: '700', color: '#1E293B', marginBottom: 4 },
    branchHintText: { fontSize: 12, color: '#94A3B8', fontWeight: '500' },
    minimalLinkBtn: { backgroundColor: '#F8FAFC', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, borderWidth: 1, borderColor: '#E2E8F0' },
    minimalLinkBtnText: { color: '#64748B', fontSize: 12, fontWeight: '600' },

    // Admin Dashboard Premium Styles
    premiumQuickActionRow: { flexDirection: 'row', gap: 12, marginBottom: 20 },
    premiumQuickBtn: { flex: 1, padding: 20, borderRadius: 24, alignItems: 'center', elevation: 4, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 8 },
    premiumQuickBtnIcon: { fontSize: 28, marginBottom: 8 },
    premiumQuickBtnTitle: { fontSize: 15, fontWeight: '800', color: '#fff', marginBottom: 4 },
    premiumQuickBtnSubtitle: { fontSize: 10, color: 'rgba(255,255,255,0.6)', fontWeight: '600' },
    premiumInfoCard: { backgroundColor: '#fff', padding: 20, borderRadius: 24, borderWidth: 1, borderColor: '#F1F5F9', elevation: 2, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.05, shadowRadius: 10 },
    premiumInfoLabel: { fontSize: 14, fontWeight: '800', color: '#1E293B' },
    premiumSmallBtn: { backgroundColor: '#F8FAFC', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8, borderWidth: 1, borderColor: '#E2E8F0' },
    premiumSmallBtnText: { color: '#64748B', fontSize: 11, fontWeight: '700' },
    premiumLinkBox: { backgroundColor: '#F8FAFC', padding: 12, borderRadius: 12, borderWidth: 1, borderColor: '#F1F5F9' },
    premiumLinkText: { fontSize: 12, color: '#4F46E5', fontWeight: '500' },
    premiumSearchBox: { marginBottom: 16 },
    premiumSearchInput: { backgroundColor: '#F8FAFC', padding: 14, borderRadius: 14, fontSize: 14, borderWidth: 1, borderColor: '#F1F5F9', color: '#1E293B' },

    // Bottom Sheet Premium Styles
    premiumBottomSheet: {
        backgroundColor: '#fff',
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        paddingHorizontal: 24,
        paddingTop: 12,
        paddingBottom: 48,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -10 },
        shadowOpacity: 0.1,
        shadowRadius: 20,
        elevation: 20
    },
    bottomSheetHandle: { width: 36, height: 4, backgroundColor: '#E2E8F0', borderRadius: 2, alignSelf: 'center', marginBottom: 24 },
    bottomSheetHeader: { marginBottom: 24 },
    bottomSheetTitle: { fontSize: 20, fontWeight: '800', color: '#1E293B', marginBottom: 4 },
    bottomSheetSubtitle: { fontSize: 13, color: '#94A3B8', fontWeight: '500' },
    premiumMenuBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 20,
        backgroundColor: '#F8FAFC',
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#F1F5F9'
    },
    menuBtnTextGroup: { flex: 1 },
    menuBtnLabel: { fontSize: 16, fontWeight: '700', color: '#1E293B', marginBottom: 4 },
    menuBtnDesc: { fontSize: 12, color: '#64748B' },
    menuBtnArrow: { fontSize: 20, color: '#CBD5E1', fontWeight: '300' },
    menuSeparator: { height: 1, backgroundColor: '#F1F5F9', marginVertical: 8 },
    premiumExitBtn: { padding: 20, borderRadius: 20, backgroundColor: '#FFF1F2', borderWidth: 1, borderColor: '#FFE4E6' },
    exitBtnLabel: { fontSize: 15, fontWeight: '700', color: '#E11D48', marginBottom: 2 },
    exitBtnDesc: { fontSize: 12, color: '#FB7185' },
});
